### ISSUE TITLE
Incompatible w/ Shaders

### ISSUE THREAD

**Issue by Valafi** [Mrbysco/Measurements#2]
## Client Info
* Minecraft Version: 1.16.5

* Forge Version: 36.1.32
* Mod Version: 1.0.0
* Java Version: Oracle 1.8.0_291 64-bit

## Issue Description
While the mod works fine with Optifine itself, it breaks the game rendering if a shader is enabled.

## Reproduce Steps
1. Install Measurements & Optifine
2. Enable the 'Internal' shaders in the shaderpack menu

**Comment by Mrbysco** [comment]
There's nothing I can do about it. Optifine is closed source and there's no readable stacktrace.

**Comment by Mrbysco** [comment]
I seem to have accidentally found the cause and fixed it. Will be fixed next release
