### ISSUE TITLE
Tape Measure Not Working on Servers?

### ISSUE THREAD

**Issue by Darkosto** [Mrbysco/Measurements#3]
While playing on a dedicated server, I crafted the tape measure and the measurements were not appearing. I recall it working on servers previously so I'm not sure what's up now. Are you able to replicate this on your server?

**Comment by Mrbysco** [comment]
I'm currently unable to reproduce it, even on a dedicated server
![image](https://user-images.githubusercontent.com/9308260/139973027-c02e9fd3-4114-4e8c-a78d-7e57bfea89a2.png)
