### ISSUE TITLE
[Suggestion]: Keep measurement visuals when switching to a different held item

### ISSUE THREAD

**Issue by Nevrai** [Mrbysco/Measurements#4]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Currently, the measurement visuals disappear when you stop holding the tape measure, which is frustrating when building. You can’t use it in your off-hand either, nor can you use blocks in your off-hand whilst holding the tape measure.

It’d be great if you could make the measurements remain when switching to a different held item! Would make it much more convenient.

**Comment by Nevrai** [comment]
Thanks for implementing this! Is this going to be added in 1.18.2 as well?

**Comment by NilsMoller** [comment]
This is not working in `Measurements-forge-1.20.1-2.0.0`

**Comment by Mrbysco** [comment]
The feature that was implemented was the ability to hold the Measuring Tape off-hand and still see the visual, not the ability to see the visuals no matter the held item
